name: most-frequent-technology-english-words

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: gulp

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Build Jekyll
      - name: build jekyll
        uses: lemonarc/jekyll-action@1.0.0

      # Push build dir into AWS S3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ./_site/ s3://learn-english.dev

      # Invalidate Cloudfront
      - name: invalidate aws cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Send Slack message
      - name: send slack notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: build-log
          SLACK_MESSAGE: "Deployment is successful"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: "#2EB887"
          SLACK_TITLE: "Message"
          SLACK_ICON: https://avatars2.githubusercontent.com/u/44036562?s=400&v=4
